import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export type Delivery = {
  id: string;
  repair_id: string;
  picked_up_by_name: string;
  picked_up_by_phone: string | null;
  handed_over_by: string;
  notes: string | null;
  delivered_at: string;
  handedOverBy: { id: string; name: string } | null;
};

// `deliveries` and `confirm_repair_delivery` aren't in the generated Database type
// (types.ts is regenerated by external tooling straight off the live schema, which
// only happens once the migrations here are actually applied there) — cast narrowly
// at these two call sites rather than hand-editing that generated file.
export function useDelivery(repairId: string | undefined) {
  return useQuery({
    queryKey: ["delivery", repairId],
    enabled: !!repairId,
    queryFn: async () => {
      const { data, error } = await (supabase.from("deliveries" as any) as any)
        .select("*, handedOverBy:profiles!deliveries_handed_over_by_fkey(id,name)")
        .eq("repair_id", repairId!)
        .maybeSingle();
      if (error) throw error;
      return data as Delivery | null;
    },
  });
}

// Goes through confirm_repair_delivery() so the status flip and the delivery
// record are inserted together, in one transaction — see the migration for why.
export function useConfirmDelivery() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: {
      repairId: string;
      pickedUpByName: string;
      pickedUpByPhone?: string | null;
      notes?: string | null;
    }) => {
      const { data, error } = await (supabase.rpc as any)("confirm_repair_delivery", {
        _repair_id: input.repairId,
        _picked_up_by_name: input.pickedUpByName,
        _picked_up_by_phone: input.pickedUpByPhone ?? null,
        _notes: input.notes ?? null,
      });
      if (error) throw error;
      return data as Delivery;
    },
    onSuccess: (d) => {
      qc.invalidateQueries({ queryKey: ["repairs"] });
      qc.invalidateQueries({ queryKey: ["repairs", "detail", d.repair_id] });
      qc.invalidateQueries({ queryKey: ["delivery", d.repair_id] });
      qc.invalidateQueries({ queryKey: ["repair-location-history", d.repair_id] });
      qc.invalidateQueries({ queryKey: ["notifications-log"] });
      // Email dispatch is handled server-side now (trg_send_email_notification via
      // pg_net, see the notifications_pg_net_dispatch migration) — no client
      // invoke needed here anymore; tg_notify_repair's insert is what fires it.
    },
  });
}
