import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export type DiagnosticChatMessage = {
  id: string;
  role: "user" | "assistant";
  message: string;
  created_at: string;
};

// `diagnostic_chats` isn't in the generated Database type yet (types.ts is
// regenerated by external tooling straight off the live schema, which only
// happens once this migration is actually applied there) — cast narrowly here
// rather than hand-editing that generated file (see use-deliveries.ts for the
// same pattern and why).
export function useDiagnosticChats(repairId: string | undefined) {
  return useQuery({
    queryKey: ["diagnostic-chats", repairId],
    enabled: !!repairId,
    queryFn: async () => {
      const { data, error } = await (supabase.from("diagnostic_chats" as any) as any)
        .select("id, role, message, created_at")
        .eq("repair_id", repairId!)
        .order("created_at", { ascending: true });
      if (error) throw error;
      return (data ?? []) as DiagnosticChatMessage[];
    },
  });
}

// Goes through the diagnostic-assistant edge function — it holds the Gemini API key
// (service role + function secret), never the browser. On success it has already
// persisted both the user's message and the assistant's reply; refetch picks them up.
export function useSendDiagnosticMessage() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { repairId: string; message: string }) => {
      const { data, error } = await supabase.functions.invoke("diagnostic-assistant", {
        body: { repair_id: input.repairId, message: input.message },
      });
      if (error) {
        // FunctionsHttpError only exposes a generic "non-2xx status code" message by
        // default — read the function's own JSON body for the real reason.
        let message = error.message;
        const ctx = (error as { context?: Response }).context;
        if (ctx && typeof ctx.json === "function") {
          try {
            const body = await ctx.json();
            if (body?.error) message = body.error;
          } catch {
            // keep the generic message
          }
        }
        throw new Error(message);
      }
      return data as { reply: string };
    },
    onSuccess: (_d, v) => qc.invalidateQueries({ queryKey: ["diagnostic-chats", v.repairId] }),
  });
}
