/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedRepairsIndexRouteImport } from './routes/_authenticated/repairs.index'
import { Route as AuthenticatedPartsIndexRouteImport } from './routes/_authenticated/parts.index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedRepairsNewRouteImport } from './routes/_authenticated/repairs.new'
import { Route as AuthenticatedRepairsRepairIdRouteImport } from './routes/_authenticated/repairs.$repairId'
import { Route as AuthenticatedPartsNewRouteImport } from './routes/_authenticated/parts.new'
import { Route as AuthenticatedPartsPartIdRouteImport } from './routes/_authenticated/parts.$partId'
import { Route as AuthenticatedNotificationsLogRouteImport } from './routes/_authenticated/notifications.log'
import { Route as AuthenticatedMachinesMachineIdRouteImport } from './routes/_authenticated/machines.$machineId'
import { Route as AuthenticatedLocationsNewRouteImport } from './routes/_authenticated/locations.new'
import { Route as AuthenticatedLocationsLocationIdRouteImport } from './routes/_authenticated/locations.$locationId'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedRepairsRepairIdEditRouteImport } from './routes/_authenticated/repairs.$repairId.edit'
import { Route as AuthenticatedPartsPartIdEditRouteImport } from './routes/_authenticated/parts.$partId.edit'
import { Route as AuthenticatedMachinesMachineIdEditRouteImport } from './routes/_authenticated/machines.$machineId.edit'
import { Route as AuthenticatedLocationsLocationIdEditRouteImport } from './routes/_authenticated/locations.$locationId.edit'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients.$clientId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepairsIndexRoute =
  AuthenticatedRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartsIndexRoute = AuthenticatedPartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepairsNewRoute = AuthenticatedRepairsNewRouteImport.update({
  id: '/repairs/new',
  path: '/repairs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepairsRepairIdRoute =
  AuthenticatedRepairsRepairIdRouteImport.update({
    id: '/repairs/$repairId',
    path: '/repairs/$repairId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartsNewRoute = AuthenticatedPartsNewRouteImport.update({
  id: '/parts/new',
  path: '/parts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsPartIdRoute =
  AuthenticatedPartsPartIdRouteImport.update({
    id: '/parts/$partId',
    path: '/parts/$partId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsLogRoute =
  AuthenticatedNotificationsLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedMachinesMachineIdRoute =
  AuthenticatedMachinesMachineIdRouteImport.update({
    id: '/machines/$machineId',
    path: '/machines/$machineId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsNewRoute =
  AuthenticatedLocationsNewRouteImport.update({
    id: '/locations/new',
    path: '/locations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsLocationIdRoute =
  AuthenticatedLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepairsRepairIdEditRoute =
  AuthenticatedRepairsRepairIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRepairsRepairIdRoute,
  } as any)
const AuthenticatedPartsPartIdEditRoute =
  AuthenticatedPartsPartIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPartsPartIdRoute,
  } as any)
const AuthenticatedMachinesMachineIdEditRoute =
  AuthenticatedMachinesMachineIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMachinesMachineIdRoute,
  } as any)
const AuthenticatedLocationsLocationIdEditRoute =
  AuthenticatedLocationsLocationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLocationsLocationIdRoute,
  } as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRouteWithChildren
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/notifications/log': typeof AuthenticatedNotificationsLogRoute
  '/parts/$partId': typeof AuthenticatedPartsPartIdRouteWithChildren
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRouteWithChildren
  '/repairs/new': typeof AuthenticatedRepairsNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/parts/': typeof AuthenticatedPartsIndexRoute
  '/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
  '/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRouteWithChildren
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/notifications/log': typeof AuthenticatedNotificationsLogRoute
  '/parts/$partId': typeof AuthenticatedPartsPartIdRouteWithChildren
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRouteWithChildren
  '/repairs/new': typeof AuthenticatedRepairsNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/parts': typeof AuthenticatedPartsIndexRoute
  '/repairs': typeof AuthenticatedRepairsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
  '/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/locations/$locationId': typeof AuthenticatedLocationsLocationIdRouteWithChildren
  '/_authenticated/locations/new': typeof AuthenticatedLocationsNewRoute
  '/_authenticated/machines/$machineId': typeof AuthenticatedMachinesMachineIdRouteWithChildren
  '/_authenticated/notifications/log': typeof AuthenticatedNotificationsLogRoute
  '/_authenticated/parts/$partId': typeof AuthenticatedPartsPartIdRouteWithChildren
  '/_authenticated/parts/new': typeof AuthenticatedPartsNewRoute
  '/_authenticated/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRouteWithChildren
  '/_authenticated/repairs/new': typeof AuthenticatedRepairsNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/parts/': typeof AuthenticatedPartsIndexRoute
  '/_authenticated/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/_authenticated/machines/$machineId/edit': typeof AuthenticatedMachinesMachineIdEditRoute
  '/_authenticated/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/_authenticated/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/notifications'
    | '/users'
    | '/clients/$clientId'
    | '/clients/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/machines/$machineId'
    | '/notifications/log'
    | '/parts/$partId'
    | '/parts/new'
    | '/repairs/$repairId'
    | '/repairs/new'
    | '/clients/'
    | '/locations/'
    | '/parts/'
    | '/repairs/'
    | '/clients/$clientId/edit'
    | '/locations/$locationId/edit'
    | '/machines/$machineId/edit'
    | '/parts/$partId/edit'
    | '/repairs/$repairId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/notifications'
    | '/users'
    | '/clients/$clientId'
    | '/clients/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/machines/$machineId'
    | '/notifications/log'
    | '/parts/$partId'
    | '/parts/new'
    | '/repairs/$repairId'
    | '/repairs/new'
    | '/clients'
    | '/locations'
    | '/parts'
    | '/repairs'
    | '/clients/$clientId/edit'
    | '/locations/$locationId/edit'
    | '/machines/$machineId/edit'
    | '/parts/$partId/edit'
    | '/repairs/$repairId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/users'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/locations/$locationId'
    | '/_authenticated/locations/new'
    | '/_authenticated/machines/$machineId'
    | '/_authenticated/notifications/log'
    | '/_authenticated/parts/$partId'
    | '/_authenticated/parts/new'
    | '/_authenticated/repairs/$repairId'
    | '/_authenticated/repairs/new'
    | '/_authenticated/clients/'
    | '/_authenticated/locations/'
    | '/_authenticated/parts/'
    | '/_authenticated/repairs/'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/locations/$locationId/edit'
    | '/_authenticated/machines/$machineId/edit'
    | '/_authenticated/parts/$partId/edit'
    | '/_authenticated/repairs/$repairId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/': {
      id: '/_authenticated/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthenticatedRepairsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts/': {
      id: '/_authenticated/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof AuthenticatedPartsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/new': {
      id: '/_authenticated/repairs/new'
      path: '/repairs/new'
      fullPath: '/repairs/new'
      preLoaderRoute: typeof AuthenticatedRepairsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/$repairId': {
      id: '/_authenticated/repairs/$repairId'
      path: '/repairs/$repairId'
      fullPath: '/repairs/$repairId'
      preLoaderRoute: typeof AuthenticatedRepairsRepairIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts/new': {
      id: '/_authenticated/parts/new'
      path: '/parts/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof AuthenticatedPartsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts/$partId': {
      id: '/_authenticated/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof AuthenticatedPartsPartIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/log': {
      id: '/_authenticated/notifications/log'
      path: '/log'
      fullPath: '/notifications/log'
      preLoaderRoute: typeof AuthenticatedNotificationsLogRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/machines/$machineId': {
      id: '/_authenticated/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof AuthenticatedMachinesMachineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/new': {
      id: '/_authenticated/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedLocationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/$locationId': {
      id: '/_authenticated/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/$repairId/edit': {
      id: '/_authenticated/repairs/$repairId/edit'
      path: '/edit'
      fullPath: '/repairs/$repairId/edit'
      preLoaderRoute: typeof AuthenticatedRepairsRepairIdEditRouteImport
      parentRoute: typeof AuthenticatedRepairsRepairIdRoute
    }
    '/_authenticated/parts/$partId/edit': {
      id: '/_authenticated/parts/$partId/edit'
      path: '/edit'
      fullPath: '/parts/$partId/edit'
      preLoaderRoute: typeof AuthenticatedPartsPartIdEditRouteImport
      parentRoute: typeof AuthenticatedPartsPartIdRoute
    }
    '/_authenticated/machines/$machineId/edit': {
      id: '/_authenticated/machines/$machineId/edit'
      path: '/edit'
      fullPath: '/machines/$machineId/edit'
      preLoaderRoute: typeof AuthenticatedMachinesMachineIdEditRouteImport
      parentRoute: typeof AuthenticatedMachinesMachineIdRoute
    }
    '/_authenticated/locations/$locationId/edit': {
      id: '/_authenticated/locations/$locationId/edit'
      path: '/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof AuthenticatedLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthenticatedLocationsLocationIdRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedClientsClientIdRoute
    }
  }
}

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsLogRoute: typeof AuthenticatedNotificationsLogRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsLogRoute: AuthenticatedNotificationsLogRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedClientsClientIdRouteChildren {
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
}

const AuthenticatedClientsClientIdRouteChildren: AuthenticatedClientsClientIdRouteChildren =
  {
    AuthenticatedClientsClientIdEditRoute:
      AuthenticatedClientsClientIdEditRoute,
  }

const AuthenticatedClientsClientIdRouteWithChildren =
  AuthenticatedClientsClientIdRoute._addFileChildren(
    AuthenticatedClientsClientIdRouteChildren,
  )

interface AuthenticatedLocationsLocationIdRouteChildren {
  AuthenticatedLocationsLocationIdEditRoute: typeof AuthenticatedLocationsLocationIdEditRoute
}

const AuthenticatedLocationsLocationIdRouteChildren: AuthenticatedLocationsLocationIdRouteChildren =
  {
    AuthenticatedLocationsLocationIdEditRoute:
      AuthenticatedLocationsLocationIdEditRoute,
  }

const AuthenticatedLocationsLocationIdRouteWithChildren =
  AuthenticatedLocationsLocationIdRoute._addFileChildren(
    AuthenticatedLocationsLocationIdRouteChildren,
  )

interface AuthenticatedMachinesMachineIdRouteChildren {
  AuthenticatedMachinesMachineIdEditRoute: typeof AuthenticatedMachinesMachineIdEditRoute
}

const AuthenticatedMachinesMachineIdRouteChildren: AuthenticatedMachinesMachineIdRouteChildren =
  {
    AuthenticatedMachinesMachineIdEditRoute:
      AuthenticatedMachinesMachineIdEditRoute,
  }

const AuthenticatedMachinesMachineIdRouteWithChildren =
  AuthenticatedMachinesMachineIdRoute._addFileChildren(
    AuthenticatedMachinesMachineIdRouteChildren,
  )

interface AuthenticatedPartsPartIdRouteChildren {
  AuthenticatedPartsPartIdEditRoute: typeof AuthenticatedPartsPartIdEditRoute
}

const AuthenticatedPartsPartIdRouteChildren: AuthenticatedPartsPartIdRouteChildren =
  {
    AuthenticatedPartsPartIdEditRoute: AuthenticatedPartsPartIdEditRoute,
  }

const AuthenticatedPartsPartIdRouteWithChildren =
  AuthenticatedPartsPartIdRoute._addFileChildren(
    AuthenticatedPartsPartIdRouteChildren,
  )

interface AuthenticatedRepairsRepairIdRouteChildren {
  AuthenticatedRepairsRepairIdEditRoute: typeof AuthenticatedRepairsRepairIdEditRoute
}

const AuthenticatedRepairsRepairIdRouteChildren: AuthenticatedRepairsRepairIdRouteChildren =
  {
    AuthenticatedRepairsRepairIdEditRoute:
      AuthenticatedRepairsRepairIdEditRoute,
  }

const AuthenticatedRepairsRepairIdRouteWithChildren =
  AuthenticatedRepairsRepairIdRoute._addFileChildren(
    AuthenticatedRepairsRepairIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRouteWithChildren
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedLocationsLocationIdRoute: typeof AuthenticatedLocationsLocationIdRouteWithChildren
  AuthenticatedLocationsNewRoute: typeof AuthenticatedLocationsNewRoute
  AuthenticatedMachinesMachineIdRoute: typeof AuthenticatedMachinesMachineIdRouteWithChildren
  AuthenticatedPartsPartIdRoute: typeof AuthenticatedPartsPartIdRouteWithChildren
  AuthenticatedPartsNewRoute: typeof AuthenticatedPartsNewRoute
  AuthenticatedRepairsRepairIdRoute: typeof AuthenticatedRepairsRepairIdRouteWithChildren
  AuthenticatedRepairsNewRoute: typeof AuthenticatedRepairsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedPartsIndexRoute: typeof AuthenticatedPartsIndexRoute
  AuthenticatedRepairsIndexRoute: typeof AuthenticatedRepairsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedClientsClientIdRoute:
    AuthenticatedClientsClientIdRouteWithChildren,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedLocationsLocationIdRoute:
    AuthenticatedLocationsLocationIdRouteWithChildren,
  AuthenticatedLocationsNewRoute: AuthenticatedLocationsNewRoute,
  AuthenticatedMachinesMachineIdRoute:
    AuthenticatedMachinesMachineIdRouteWithChildren,
  AuthenticatedPartsPartIdRoute: AuthenticatedPartsPartIdRouteWithChildren,
  AuthenticatedPartsNewRoute: AuthenticatedPartsNewRoute,
  AuthenticatedRepairsRepairIdRoute:
    AuthenticatedRepairsRepairIdRouteWithChildren,
  AuthenticatedRepairsNewRoute: AuthenticatedRepairsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedPartsIndexRoute: AuthenticatedPartsIndexRoute,
  AuthenticatedRepairsIndexRoute: AuthenticatedRepairsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
